<?xml version="1.0"?>

<robot name="hanging_cylinder" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="hanging_cylinder" params="parent radius:=0.025 length:=0.4">
    <!--<xacro:property name="width" value="0.2" />
    <xacro:property name="bodylen" value="0.6" /> -->
    <link name="hanging_cylinder">

      <intertial>
          <mass>0.15</mass>
      </intertial>

      <visual>
          <geometry>
              <cylinder radius="${radius}" length="${length}"/>
          </geometry>
          <!--<material name="red"/> -->
      </visual>
      <collision>
          <geometry>
              <cylinder radius="${radius}" length="${length}"/>
          </geometry>
      </collision>
    </link>

  <gazebo reference="hanging_cylinder">
        <material>Gazebo/Red</material>
        <sensor name='hanging_cylinder_bumper' type='contact'>
	        <always_on>true</always_on>
            <contact>
              <collision>hummingbird/base_link_fixed_joint_lump__hanging_cylinder_collision</collision>
            </contact>
            <update_rate> 5 </update_rate>
            <plugin name="grimpper" filename="libgazebo_ros_bumper.so">
              <bumperTopicName>bumper</bumperTopicName>
              <frameName>world</frameName>
            </plugin>
        </sensor>
  </gazebo>
    
    <joint name="base_to_hanging_cylinder" type="fixed">
        <parent link="${parent}"/>
        <child link="hanging_cylinder"/>
        <origin xyz="0 0 -${length/2}" />
    </joint>
    
  </xacro:macro>


  <xacro:macro name="add_main_bumper" params="parent">

      <gazebo reference="hummingbird/base_link">
            <sensor name='base_link_main_collision_bumper' type='contact'>
                <always_on>true</always_on>
                <contact>
                  <collision>hummingbird/base_link_inertia_collision_1</collision>
                </contact>
                <update_rate> 5 </update_rate>
                <plugin name="base_link_main_collision_bumper" filename="libgazebo_ros_bumper.so">
                  <bumperTopicName>bumper</bumperTopicName>
                  <frameName>world</frameName>
                </plugin>
            </sensor>
      </gazebo>

  </xacro:macro>

</robot>
